# Generated by Django 3.2.10 on 2022-03-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('publicated_at', models.DateTimeField(verbose_name='date published')),
                ('creator', models.CharField(max_length=256)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('article_categories', models.ManyToManyField(to='startups.Categories')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
