# Generated by Django 3.2.9 on 2022-08-11 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=256)),
                ('market', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('approoved', models.BooleanField(default=False)),
                ('publicated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TagGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('publicated_at', models.DateTimeField(verbose_name='date published')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('publicated_at', models.DateTimeField(verbose_name='date published')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('tag_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startups_tags', models.ManyToManyField(to='startups.TagGroups')),
            ],
        ),
        migrations.CreateModel(
            name='Founds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('approoved', models.BooleanField(default=False)),
                ('publicated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startups')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('publicated_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=256)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('article_categories', models.ManyToManyField(to='startups.Categories')),
            ],
        ),
    ]
