# Generated by Django 3.2.10 on 2022-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startups_taggroups_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggroups',
            name='tag_group_id',
        ),
        migrations.AlterField(
            model_name='tags',
            name='startups_tags',
            field=models.ManyToManyField(to='startups.TagGroups'),
        ),
    ]
