# Generated by Django 3.2.10 on 2022-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_auto_20220329_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startups',
            name='approoved',
            field=models.BooleanField(default=False),
        ),
    ]
