# Generated by Django 3.2.10 on 2022-04-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_auto_20220331_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='startups',
            options={'verbose_name_plural': 'Startups'},
        ),
        migrations.AlterModelOptions(
            name='taggroups',
            options={'verbose_name_plural': 'Tags group'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
