# Generated by Django 3.2.10 on 2022-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_auto_20220405_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publicated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
