# Generated by Django 3.2.9 on 2022-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_founds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
