# Generated by Django 3.2.9 on 2022-08-10 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0008_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='founds',
            name='publicated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
